import { createRequire } from 'module';
import { spawn } from 'child_process';
const require = createRequire(import.meta.url);
const { chromium, devices } = require('/opt/node22/lib/node_modules/playwright');
const server = spawn('npx', ['vite', 'preview', '--port', '4176', '--strictPort'], { stdio: 'pipe' });
await new Promise((r) => setTimeout(r, 2500));
const browser = await chromium.launch({ args: ['--use-gl=angle', '--use-angle=swiftshader', '--enable-unsafe-swiftshader'] });
const ctx = await browser.newContext({ ...devices['iPhone 13 landscape'] });
const page = await ctx.newPage();
const errors = [];
page.on('console', (m) => errors.push(`[${m.type()}] ${m.text()}`));
page.on('pageerror', (e) => errors.push(`[pageerror] ${e.message} ${e.stack}`));
await page.goto('http://localhost:4176/');
await page.waitForFunction(() => window.__game, null, { timeout: 60000 });
await page.waitForTimeout(1500);
await page.evaluate(() => { for (const t of ['pointerdown','pointerup','touchstart','touchend','click']) window.addEventListener(t, (e) => console.log('EV', t, e.target.className || e.target.tagName, e.defaultPrevented), true); });
const box = await page.locator('.btn.play').boundingBox();
console.log('play box', box);
await page.touchscreen.tap(box.x + box.width / 2, box.y + box.height / 2);
await page.waitForTimeout(3000);
const st = await page.evaluate(() => { const g = window.__game; return { paused: g.isPaused, touch: g.input.s.touchActive, cam: g.camera.position.toArray(), time: g.time }; });
console.log(st);
await page.screenshot({ path: 'tools/out/tapplay.png' });
const pb = await page.locator('.pausebtn').boundingBox();
await page.touchscreen.tap(pb.x + pb.width / 2, pb.y + pb.height / 2);
await page.waitForTimeout(800);
console.log('after pause tap paused=', await page.evaluate(() => window.__game.isPaused)); await page.screenshot({ path: 'tools/out/pause-m.png' });
const rb = await page.locator('.btn.resume').boundingBox();
await page.touchscreen.tap(rb.x + rb.width / 2, rb.y + rb.height / 2);
await page.waitForTimeout(800);
console.log('after resume tap paused=', await page.evaluate(() => window.__game.isPaused));
console.log(errors.join('\n'));
await browser.close(); server.kill(); process.exit(0);
